# Generated by Django 4.1.13 on 2024-05-16 02:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('neighborthood', models.CharField(max_length=100, verbose_name='Neighborthood')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
            ],
        ),
    ]
