# Generated by Django 4.1.13 on 2024-05-16 23:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Pasillo', 'Pasillo'), ('Estantería', 'Estantería'), ('Rack', 'Rack'), ('Slot', 'Slot'), ('Posición de Pallet', 'Posición de Pallet'), ('Ubicación de Contenedor', 'Ubicación de Contenedor'), ('Zona de Recolección', 'Zona de Recolección'), ('Área de Consolidación', 'Área de Consolidación'), ('Área de Recepción', 'Área de Recepción'), ('Área de Envío', 'Área de Envío'), ('Almacenamiento a Granel', 'Almacenamiento a Granel'), ('Almacenamiento en Frío', 'Almacenamiento en Frío'), ('Almacenamiento de Materiales Peligrosos', 'Almacenamiento de Materiales Peligrosos'), ('Área de Desbordamiento', 'Área de Desbordamiento'), ('Área de Devoluciones', 'Área de Devoluciones')], max_length=70, verbose_name='Type')),
                ('long', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Long')),
                ('high', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='High')),
                ('width', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Width')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Weight')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('neighborthood', models.CharField(max_length=100, verbose_name='Neighborthood')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='authApp.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='authApp.location'),
        ),
    ]
